resolve review comments
sahilbhatia/github-quest pull request #50
Opened 2020-10-08 06:02 UTC by avi4630

2020-10-19 05:42 UTC, sunil4sonawane requested changes
check comments

2020-10-19 05:42 UTC, sunil4sonawane commented on models/sequelize.js
> +// db.roles = require("./roles.model")(sequelize, Sequelize);
why commented code here?

2020-10-19 05:42 UTC, sunil4sonawane commented on src/pages/api/find-project.js
> +    logger.error("Error executing in while find projects");
grammar mistake

2020-10-20 06:03 UTC, sunil4sonawane requested changes
check comments

2020-10-20 06:03 UTC, sunil4sonawane commented on models/sequelize.js
>  db.sequelize = sequelize;
why double initialisation here?

2020-10-20 06:20 UTC, avi4630 commented on models/sequelize.js
>  db.sequelize = sequelize;
this are two different objects (sequelize, Sequelize)

2020-10-20 07:57 UTC, sunil4sonawane commented on models/sequelize.js
>  db.sequelize = sequelize;
same names makes conflict(Keep in mind when your code runs on windows case sensitivity will be simply ignored). Also what is the purpose of having these two objects?

2020-10-20 09:14 UTC, sunil4sonawane approved these changes

2020-10-20 09:46 UTC, merged